version: '3.9'

networks:
  ros:
    driver: bridge
    network_mode: service:ros-master #host

services:
  ros-master:
    image: magicdan/ros-master:latest
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  teleop:
    image: magicdan/ros-teleop
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=teleop"
    volumes:
      - /dev/input/js0:/dev/input/js0
    command: stdbuf -o L roslaunch teleop_twist_joy teleop.launch
    networks:
      - ros
    restart: always

  rviz:
    image: magicdan/ros-rviz
    networks:
      - ros
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=rviz"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: stdbuf -o L rostopic echo /joy
    restart: always
