version: '3.9'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: magicdan/ros-master-full:latest
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros-master"
    build: .
    command: roscore
    restart: always

  teleop:
    image: magicdan/ros-teleop-full
    networks:
      - ros
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=teleop"
    privileged: true
    volumes:
      - /dev/input/js0:/dev/input/js0
    command: rosrun teleop_twist_joy teleop.py
    restart: on-failure:3

  teleop2:
    image: magicdan/ros-teleop-full
    networks:
      - ros
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=teleop2"
    privileged: true

    command: python /catkin_ws/src/teleop/src/teleop.py
    restart: on-failure:3

  rostopic:
    image: magicdan/ros-master:latest
    networks:
      - ros
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=rostopic"
    build: .
    command: rostopic echo /joy
    restart: always
    #on-failure:3


  
