version: '3.9'
services:
  ros-master:
    image: magicdan/ros-master:latest
    command: stdbuf -o L roscore
    restart: always
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros-master"

  teleop:
    image: magicdan/ros-teleop
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=teleop"
    privileged: true
    volumes:
      - /dev/input/js0:/dev/input/js0
    command: stdbuf -o L roslaunch teleop_twist_joy teleop.launch
    restart: always

  turtlesim:
    image: magicdan/turtlesim
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=turtlesim"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: stdbuf -o L rosrun turtlesim turtlesim_node
    restart: always

  rostopic:
    image: magicdan/ros-master
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=rostopic"
    command: stdbuf -o L rostopic echo /cmd_vel
    restart: always
  
