from magicdan/ros-master

RUN apt-get update && apt-get install ros-melodic-teleop-twist-joy -y --no-install-recommends \
ros-melodic-teleop-twist-keyboard   \
ros-melodic-joystick-drivers \
ros-melodic-joy
